package datamanagement;

import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

public class CheckGradeUserInterface extends javax.swing.JFrame implements InterfaceUnitLister, InterfaceStudentLister {
	private CheckGradeControl control_;
	private javax.swing.DefaultComboBoxModel unitModel_;
	private javax.swing.DefaultComboBoxModel recordModel_;
	float assignment1;
	float assignment2;
	float exam;
	int selectedId;

	
	
	public CheckGradeUserInterface(CheckGradeControl control) {
		this.control_ = control;
		unitModel_ = new javax.swing.DefaultComboBoxModel(new String[0]);
		recordModel_ = new javax.swing.DefaultComboBoxModel(new String[0]);
		initComponents();
		unitComboBox.setModel(unitModel_);
		studentComboBox.setModel(recordModel_);
		errorLabel.setText("");
	}

	
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		programHeaderLabel = new javax.swing.JLabel();
		unitsPanel = new javax.swing.JPanel();
		unitComboBox = new javax.swing.JComboBox();
		studentPanel = new javax.swing.JPanel();
		studentComboBox = new javax.swing.JComboBox();
		marksPanel = new javax.swing.JPanel();
		assignment1Label = new javax.swing.JLabel();
		assignment2Label = new javax.swing.JLabel();
		examLabel = new javax.swing.JLabel();
		assignment1Field = new javax.swing.JTextField();
		assignment2Field = new javax.swing.JTextField();
		examField = new javax.swing.JTextField();
		changeButton = new javax.swing.JButton();
		gradePanel = new javax.swing.JPanel();
		gradeLabel = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		programHeaderLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
		programHeaderLabel.setText("Check Grade UI");

		unitsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Unit"));

		unitComboBox.setModel(unitModel_);
		unitComboBox.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent event) {
				jComboBox1ItemStateChanged(event);
			}
		});

		
		
		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(unitsPanel);
		unitsPanel.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addComponent(unitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 185,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addComponent(unitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		studentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Student"));

		studentComboBox.setModel(recordModel_);
		studentComboBox.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent event) {
				jComboBox2ItemStateChanged(event);
			}
		});

		
		
		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(studentPanel);
		studentPanel.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap()
						.addComponent(studentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 185,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addComponent(studentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		marksPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Marks"));

		assignment1Label.setText("Assignment 1:");

		assignment2Label.setText("Assignment 2:");

		examLabel.setText("Exam:");

		assignment1Field.setEditable(false);
		assignment1Field.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent event) {
				jTextFieldKeyTyped(event);
			}
		});

		
		
		assignment2Field.setEditable(false);
		assignment2Field.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent event) {
				jTextFieldKeyTyped(event);
			}
		});

		
		
		examField.setEditable(false);
		examField.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent event) {
				jTextFieldKeyTyped(event);
			}
		});

		
		
		changeButton.setText("Change");
		changeButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent event) {
				jButton1ActionPerformed(event);
			}
		});

		
		
		checkGradeButton = new javax.swing.JButton();

		checkGradeButton.setText("Check Grade");
		checkGradeButton.setActionCommand("checkGrade");
		checkGradeButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent event) {
				jButton3ActionPerformed(event);
			}
		});

		
		
		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(marksPanel);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup()
						.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel3Layout.createSequentialGroup().addContainerGap().addComponent(assignment1Label)
										.addPreferredGap(ComponentPlacement.RELATED)
										.addComponent(assignment1Field, GroupLayout.PREFERRED_SIZE, 59,
												GroupLayout.PREFERRED_SIZE)
										.addGap(18).addComponent(assignment2Label))
						.addGroup(jPanel3Layout.createSequentialGroup().addGap(85).addComponent(changeButton,
								GroupLayout.PREFERRED_SIZE, 84, GroupLayout.PREFERRED_SIZE)))
				.addGap(18)
				.addGroup(
						jPanel3Layout.createParallelGroup(Alignment.TRAILING)
								.addGroup(jPanel3Layout.createSequentialGroup()
										.addComponent(assignment2Field, GroupLayout.PREFERRED_SIZE, 59,
												GroupLayout.PREFERRED_SIZE)
										.addGap(18).addComponent(examLabel))
								.addComponent(checkGradeButton))
						.addGap(18)
						.addComponent(examField, GroupLayout.PREFERRED_SIZE, 59, GroupLayout.PREFERRED_SIZE)
						.addGap(15)));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup()
						.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE).addComponent(assignment1Label)
								.addComponent(assignment1Field, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
						.addComponent(assignment2Label)
						.addComponent(assignment2Field, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE).addComponent(examLabel).addComponent(examField,
										GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(ComponentPlacement.UNRELATED).addGroup(jPanel3Layout
								.createParallelGroup(Alignment.BASELINE).addComponent(changeButton).addComponent(checkGradeButton))
				.addContainerGap()));
		marksPanel.setLayout(jPanel3Layout);

		gradePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Grade"));

		gradeLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		gradeLabel.setForeground(new java.awt.Color(255, 0, 0));
		gradeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		gradeLabel.setText("grade");

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(gradePanel);
		gradePanel.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(gradeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
						153, Short.MAX_VALUE));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addGap(34, 34, 34).addComponent(gradeLabel)
						.addContainerGap(43, Short.MAX_VALUE)));

		errorLabel = new JLabel();
		errorLabel.setText("Error message");
		errorLabel.setForeground(Color.RED);
		errorLabel.setFont(new Font("Tahoma", Font.PLAIN, 12));
		saveButton = new javax.swing.JButton();

		saveButton.setText("Save");
		saveButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent event) {
				jButton2ActionPerformed(event);
			}
		});

		
		
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
				layout.createParallelGroup(Alignment.LEADING)
						.addGroup(
								layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(Alignment.LEADING)
												.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(
														errorLabel, GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
						.addGroup(layout.createSequentialGroup().addContainerGap()
								.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
										.addComponent(marksPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(Alignment.LEADING)
												.addComponent(unitsPanel, GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
												.addComponent(studentPanel, GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
										.addGap(18).addComponent(gradePanel, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
						.addGroup(layout.createSequentialGroup().addGap(157).addComponent(programHeaderLabel))
						.addGroup(layout.createSequentialGroup().addGap(187).addComponent(saveButton,
								GroupLayout.PREFERRED_SIZE, 86, GroupLayout.PREFERRED_SIZE))).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(layout.createSequentialGroup()
				.addContainerGap().addComponent(programHeaderLabel).addGap(13)
				.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addComponent(unitsPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.RELATED).addComponent(studentPanel,
										GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE))
						.addComponent(gradePanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(marksPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(ComponentPlacement.RELATED).addComponent(saveButton).addGap(11)
				.addComponent(errorLabel, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE).addContainerGap()));
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	
	
	private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent event) {// GEN-FIRST:event_jComboBox1ItemStateChanged
		String currentUnit = (String) unitComboBox.getSelectedItem();
		Refresh3();
		clearStudents();
		if (event.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
			if (currentUnit.equals((String) unitComboBox.getItemAt(0))) {
				currentUnit = "NONE";
			}
			control_.unitSelected(currentUnit);
		}
	}// GEN-LAST:event_jComboBox1ItemStateChanged

	
	
	private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent event) {// GEN-FIRST:event_jComboBox2ItemStateChanged
		Refresh3();
		String currentStudent = (String) studentComboBox.getSelectedItem();
		if (event.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
			if (currentStudent.equals((String) studentComboBox.getItemAt(0))) {
				selectedId = new Integer(0);
				control_.studentSelected(selectedId);
			} else {
				selectedId = new Integer(currentStudent.split("\\s")[0]);
			}
			control_.studentSelected(selectedId);
		}
	}// GEN-LAST:event_jComboBox2ItemStateChanged

	
	
	private void jButton3ActionPerformed(java.awt.event.ActionEvent event) {// GEN-FIRST:event_jButton3ActionPerformed
		assignment1 = new Float(assignment1Field.getText()).floatValue();
		assignment2 = new Float(assignment2Field.getText()).floatValue();
		exam = new Float(examField.getText()).floatValue();
		// lblErrMsg.setText("");
		try {
			String string = control_.checkGrade(assignment1, assignment2, exam);
			gradeLabel.setText(string);
		} catch (RuntimeException runtimeException) {
			errorLabel.setText(runtimeException.getMessage());
		}
	}// GEN-LAST:event_jButton3ActionPerformed

	
	
	private void jButton1ActionPerformed(java.awt.event.ActionEvent event) {// GEN-FIRST:event_jButton1ActionPerformed
		control_.enableChangeMarks();
		gradeLabel.setText("");
		// lblErrMsg.setText("");
	}// GEN-LAST:event_jButton1ActionPerformed

	
	
	private void jTextFieldKeyTyped(java.awt.event.KeyEvent event) {// GEN-FIRST:event_jTextField1KeyTyped
		gradeLabel.setText("");
		errorLabel.setText("");
	}// GEN-LAST:event_jTextField1KeyTyped

	
	
	private void jButton2ActionPerformed(java.awt.event.ActionEvent event) {// GEN-FIRST:event_jButton2ActionPerformed
		float aassignment1 = new Float(assignment1Field.getText()).floatValue();
		float assignment2 = new Float(assignment2Field.getText()).floatValue();
		float exam = new Float(examField.getText()).floatValue();
		errorLabel.setText("");
		try {
			control_.saveGrade(aassignment1, assignment2, exam);
			// jButton3ActionPerformed(null);
		} catch (RuntimeException runtimeException) {
			errorLabel.setText(runtimeException.getMessage());
		}
	}// GEN-LAST:event_jButton2ActionPerformed

	
	
	public void clearUnits() {
		unitModel_.removeAllElements();
		unitModel_.addElement("<none selected>");
		clearStudents();
	}

	
	
	public void addUnit(InterfaceUnit unit) {
		unitModel_.addElement(unit.getUnitCode());
	}

	
	
	public void setState1(boolean isEnabled) {
		unitComboBox.setEnabled(isEnabled);
		errorLabel.setText("");
	}

	
	
	public void clearStudents() {
		recordModel_.removeAllElements();
		recordModel_.addElement("<none selected>");
	}

	
	
	public void addStudent(InterfaceStudent student) {
		recordModel_
				.addElement(student.getID().toString() + " : " + student.getFirstName() + " " + student.getLastName());
	}

	
	
	public void setState2(boolean isEnabled) {
		studentComboBox.setEnabled(isEnabled);
		errorLabel.setText("");
	}

	
	
	public void setRecord(InterfaceStudentUnitRecord record) {
		assignment1Field.setText(new Float(record.getAssignment1Mark()).toString());
		assignment2Field.setText(new Float(record.getAssignment2Mark()).toString());
		examField.setText(new Float(record.getExamMark()).toString());
		gradeLabel.setText("");
	}

	
	
	public void Refresh3() {
		assignment1Field.setText("");
		assignment2Field.setText("");
		examField.setText("");
		gradeLabel.setText("");
		errorLabel.setText("");
		assignment1Field.setEditable(false);
		assignment2Field.setEditable(false);
		examField.setEditable(false);
	}

	
	
	public void setState3(boolean isEnabled) {
		checkGradeButton.setEnabled(isEnabled);
	}

	
	
	public void setState4(boolean isEnabled) {
		changeButton.setEnabled(isEnabled);
		// gradeLB.setText("");
	}

	
	
	public void setState5(boolean isEnabled) {
		assignment1Field.setEditable(isEnabled);
		assignment2Field.setEditable(isEnabled);
		examField.setEditable(isEnabled);
	}

	
	
	public void setState6(boolean isEnabled) {
		saveButton.setEnabled(isEnabled);
	}

	
	
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton changeButton;
	private javax.swing.JButton checkGradeButton;
	private javax.swing.JButton saveButton;
	private javax.swing.JComboBox unitComboBox;
	private javax.swing.JComboBox studentComboBox;
	private javax.swing.JLabel programHeaderLabel;
	private javax.swing.JLabel assignment1Label;
	private javax.swing.JLabel assignment2Label;
	private javax.swing.JLabel examLabel;
	private javax.swing.JLabel gradeLabel;
	private javax.swing.JLabel errorLabel;
	private javax.swing.JPanel unitsPanel;
	private javax.swing.JPanel studentPanel;
	private javax.swing.JPanel marksPanel;
	private javax.swing.JPanel gradePanel;
	private javax.swing.JTextField assignment1Field;
	private javax.swing.JTextField assignment2Field;
	private javax.swing.JTextField examField;
}
