package datamanagement;

import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;



public class CheckGradeUserInterface extends javax.swing.JFrame implements InterfaceUnitLister, InterfaceStudentLister {
	private CheckGradeControl control_;
	private javax.swing.DefaultComboBoxModel unitModel_;
	private javax.swing.DefaultComboBoxModel recordModel_;
	float assignment1;
	float assignment2;
	float exam;
	int selectedId;

	
	
	public CheckGradeUserInterface(CheckGradeControl control) {
		this.control_ = control;
		unitModel_ = new javax.swing.DefaultComboBoxModel(new String[0]);
		recordModel_ = new javax.swing.DefaultComboBoxModel(new String[0]);
		initComponents();
		unitComboBox_.setModel(unitModel_);
		studentComboBox_.setModel(recordModel_);
		errorLabel_.setText("");
	}

	
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		programHeaderLabel_ = new javax.swing.JLabel();
		unitsPanel_ = new javax.swing.JPanel();
		unitComboBox_ = new javax.swing.JComboBox();
		studentPanel_ = new javax.swing.JPanel();
		studentComboBox_ = new javax.swing.JComboBox();
		marksPanel_ = new javax.swing.JPanel();
		assignment1Label_ = new javax.swing.JLabel();
		assignment2Label_ = new javax.swing.JLabel();
		examLabel_ = new javax.swing.JLabel();
		assignment1Field_ = new javax.swing.JTextField();
		assignment2Field_ = new javax.swing.JTextField();
		examField_ = new javax.swing.JTextField();
		changeButton_ = new javax.swing.JButton();
		gradePanel_ = new javax.swing.JPanel();
		gradeLabel_ = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		programHeaderLabel_.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
		programHeaderLabel_.setText("Check Grade UI");

		unitsPanel_.setBorder(javax.swing.BorderFactory.createTitledBorder("Unit"));

		unitComboBox_.setModel(unitModel_);
		unitComboBox_.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent event) {
				jComboBox1ItemStateChanged(event);
			}
		});

		
		
		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(unitsPanel_);
		unitsPanel_.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addComponent(unitComboBox_, javax.swing.GroupLayout.PREFERRED_SIZE, 185,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addComponent(unitComboBox_, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		studentPanel_.setBorder(javax.swing.BorderFactory.createTitledBorder("Student"));

		studentComboBox_.setModel(recordModel_);
		studentComboBox_.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent event) {
				jComboBox2ItemStateChanged(event);
			}
		});

		
		
		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(studentPanel_);
		studentPanel_.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap()
						.addComponent(studentComboBox_, javax.swing.GroupLayout.PREFERRED_SIZE, 185,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addComponent(studentComboBox_, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		marksPanel_.setBorder(javax.swing.BorderFactory.createTitledBorder("Marks"));

		assignment1Label_.setText("Assignment 1:");

		assignment2Label_.setText("Assignment 2:");

		examLabel_.setText("Exam:");

		assignment1Field_.setEditable(false);
		assignment1Field_.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent event) {
				jTextFieldKeyTyped(event);
			}
		});

		
		
		assignment2Field_.setEditable(false);
		assignment2Field_.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent event) {
				jTextFieldKeyTyped(event);
			}
		});

		
		
		examField_.setEditable(false);
		examField_.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent event) {
				jTextFieldKeyTyped(event);
			}
		});

		
		
		changeButton_.setText("Change");
		changeButton_.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent event) {
				jButton1ActionPerformed(event);
			}
		});

		
		
		checkGradeButton_ = new javax.swing.JButton();

		checkGradeButton_.setText("Check Grade");
		checkGradeButton_.setActionCommand("checkGrade");
		checkGradeButton_.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent event) {
				jButton3ActionPerformed(event);
			}
		});

		
		
		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(marksPanel_);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup()
						.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel3Layout.createSequentialGroup().addContainerGap().addComponent(assignment1Label_)
										.addPreferredGap(ComponentPlacement.RELATED)
										.addComponent(assignment1Field_, GroupLayout.PREFERRED_SIZE, 59,
												GroupLayout.PREFERRED_SIZE)
										.addGap(18).addComponent(assignment2Label_))
						.addGroup(jPanel3Layout.createSequentialGroup().addGap(85).addComponent(changeButton_,
								GroupLayout.PREFERRED_SIZE, 84, GroupLayout.PREFERRED_SIZE)))
				.addGap(18)
				.addGroup(
						jPanel3Layout.createParallelGroup(Alignment.TRAILING)
								.addGroup(jPanel3Layout.createSequentialGroup()
										.addComponent(assignment2Field_, GroupLayout.PREFERRED_SIZE, 59,
												GroupLayout.PREFERRED_SIZE)
										.addGap(18).addComponent(examLabel_))
								.addComponent(checkGradeButton_))
						.addGap(18)
						.addComponent(examField_, GroupLayout.PREFERRED_SIZE, 59, GroupLayout.PREFERRED_SIZE)
						.addGap(15)));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup()
						.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE).addComponent(assignment1Label_)
								.addComponent(assignment1Field_, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
						.addComponent(assignment2Label_)
						.addComponent(assignment2Field_, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE).addComponent(examLabel_).addComponent(examField_,
										GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(ComponentPlacement.UNRELATED).addGroup(jPanel3Layout
								.createParallelGroup(Alignment.BASELINE).addComponent(changeButton_).addComponent(checkGradeButton_))
				.addContainerGap()));
		marksPanel_.setLayout(jPanel3Layout);

		gradePanel_.setBorder(javax.swing.BorderFactory.createTitledBorder("Grade"));

		gradeLabel_.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		gradeLabel_.setForeground(new java.awt.Color(255, 0, 0));
		gradeLabel_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		gradeLabel_.setText("grade");

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(gradePanel_);
		gradePanel_.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(gradeLabel_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
						153, Short.MAX_VALUE));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addGap(34, 34, 34).addComponent(gradeLabel_)
						.addContainerGap(43, Short.MAX_VALUE)));

		errorLabel_ = new JLabel();
		errorLabel_.setText("Error message");
		errorLabel_.setForeground(Color.RED);
		errorLabel_.setFont(new Font("Tahoma", Font.PLAIN, 12));
		saveButton_ = new javax.swing.JButton();

		saveButton_.setText("Save");
		saveButton_.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent event) {
				jButton2ActionPerformed(event);
			}
		});

		
		
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
				layout.createParallelGroup(Alignment.LEADING)
						.addGroup(
								layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(Alignment.LEADING)
												.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(
														errorLabel_, GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
						.addGroup(layout.createSequentialGroup().addContainerGap()
								.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
										.addComponent(marksPanel_, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(Alignment.LEADING)
												.addComponent(unitsPanel_, GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
												.addComponent(studentPanel_, GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
										.addGap(18).addComponent(gradePanel_, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
						.addGroup(layout.createSequentialGroup().addGap(157).addComponent(programHeaderLabel_))
						.addGroup(layout.createSequentialGroup().addGap(199).addComponent(saveButton_,
								GroupLayout.PREFERRED_SIZE, 86, GroupLayout.PREFERRED_SIZE))).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(layout.createSequentialGroup()
				.addContainerGap().addComponent(programHeaderLabel_).addGap(13)
				.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addComponent(unitsPanel_, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.RELATED).addComponent(studentPanel_,
										GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE))
						.addComponent(gradePanel_, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(marksPanel_, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(ComponentPlacement.RELATED).addComponent(saveButton_).addGap(11)
				.addComponent(errorLabel_, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE).addContainerGap()));
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	
	
	private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent event) {// GEN-FIRST:event_jComboBox1ItemStateChanged
		String currentUnit = (String) unitComboBox_.getSelectedItem();
		Refresh3();
		clearStudents();
		if (event.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
			if (currentUnit.equals((String) unitComboBox_.getItemAt(0))) {
				currentUnit = "NONE";
			}
			control_.unitSelected(currentUnit);
		}
	}// GEN-LAST:event_jComboBox1ItemStateChanged

	
	
	private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent event) {// GEN-FIRST:event_jComboBox2ItemStateChanged
		Refresh3();
		String currentStudent = (String) studentComboBox_.getSelectedItem();
		if (event.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
			if (currentStudent.equals((String) studentComboBox_.getItemAt(0))) {
				selectedId = new Integer(0);
				control_.studentSelected(selectedId);
			} else {
				selectedId = new Integer(currentStudent.split("\\s")[0]);
			}
			control_.studentSelected(selectedId);
		}
	}// GEN-LAST:event_jComboBox2ItemStateChanged

	
	
	private void jButton3ActionPerformed(java.awt.event.ActionEvent event) {// GEN-FIRST:event_jButton3ActionPerformed
		assignment1 = new Float(assignment1Field_.getText()).floatValue();
		assignment2 = new Float(assignment2Field_.getText()).floatValue();
		exam = new Float(examField_.getText()).floatValue();
		// lblErrMsg.setText("");
		try {
			String string = control_.checkGrade(assignment1, assignment2, exam);
			gradeLabel_.setText(string);
		} catch (RuntimeException runtimeException) {
			errorLabel_.setText(runtimeException.getMessage());
		}
	}// GEN-LAST:event_jButton3ActionPerformed

	
	
	private void jButton1ActionPerformed(java.awt.event.ActionEvent event) {// GEN-FIRST:event_jButton1ActionPerformed
		control_.enableChangeMarks();
		gradeLabel_.setText("");
		// lblErrMsg.setText("");
	}// GEN-LAST:event_jButton1ActionPerformed

	
	
	private void jTextFieldKeyTyped(java.awt.event.KeyEvent event) {// GEN-FIRST:event_jTextField1KeyTyped
		gradeLabel_.setText("");
		errorLabel_.setText("");
	}// GEN-LAST:event_jTextField1KeyTyped

	
	
	private void jButton2ActionPerformed(java.awt.event.ActionEvent event) {// GEN-FIRST:event_jButton2ActionPerformed
		float aassignment1 = new Float(assignment1Field_.getText()).floatValue();
		float assignment2 = new Float(assignment2Field_.getText()).floatValue();
		float exam = new Float(examField_.getText()).floatValue();
		errorLabel_.setText("");
		try {
			control_.saveGrade(aassignment1, assignment2, exam);
			// jButton3ActionPerformed(null);
		} catch (RuntimeException runtimeException) {
			errorLabel_.setText(runtimeException.getMessage());
		}
	}// GEN-LAST:event_jButton2ActionPerformed

	
	
	public void clearUnits() {
		unitModel_.removeAllElements();
		unitModel_.addElement("<none selected>");
		clearStudents();
	}

	
	
	public void addUnit(InterfaceUnit unit) {
		unitModel_.addElement(unit.getUnitCode());
	}

	
	
	public void setState1(boolean isEnabled) {
		unitComboBox_.setEnabled(isEnabled);
		errorLabel_.setText("");
	}

	
	
	public void clearStudents() {
		recordModel_.removeAllElements();
		recordModel_.addElement("<none selected>");
	}

	
	
	public void addStudent(InterfaceStudent student) {
		recordModel_
				.addElement(student.getID().toString() + " : " + student.getFirstName() + " " + student.getLastName());
	}

	
	
	public void setState2(boolean isEnabled) {
		studentComboBox_.setEnabled(isEnabled);
		errorLabel_.setText("");
	}

	
	
	public void setRecord(InterfaceStudentUnitRecord record) {
		assignment1Field_.setText(new Float(record.getAssignment1Mark()).toString());
		assignment2Field_.setText(new Float(record.getAssignment2Mark()).toString());
		examField_.setText(new Float(record.getExamMark()).toString());
		gradeLabel_.setText("");
	}

	
	
	public void Refresh3() {
		assignment1Field_.setText("");
		assignment2Field_.setText("");
		examField_.setText("");
		gradeLabel_.setText("");
		errorLabel_.setText("");
		assignment1Field_.setEditable(false);
		assignment2Field_.setEditable(false);
		examField_.setEditable(false);
	}

	
	
	public void setState3(boolean isEnabled) {
		checkGradeButton_.setEnabled(isEnabled);
	}

	
	
	public void setState4(boolean isEnabled) {
		changeButton_.setEnabled(isEnabled);
		// gradeLB.setText("");
	}

	
	
	public void setState5(boolean isEnabled) {
		assignment1Field_.setEditable(isEnabled);
		assignment2Field_.setEditable(isEnabled);
		examField_.setEditable(isEnabled);
	}

	
	
	public void setState6(boolean isEnabled) {
		saveButton_.setEnabled(isEnabled);
	}

	
	
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton changeButton_;
	private javax.swing.JButton checkGradeButton_;
	private javax.swing.JButton saveButton_;
	private javax.swing.JComboBox unitComboBox_;
	private javax.swing.JComboBox studentComboBox_;
	private javax.swing.JLabel programHeaderLabel_;
	private javax.swing.JLabel assignment1Label_;
	private javax.swing.JLabel assignment2Label_;
	private javax.swing.JLabel examLabel_;
	private javax.swing.JLabel gradeLabel_;
	private javax.swing.JLabel errorLabel_;
	private javax.swing.JPanel unitsPanel_;
	private javax.swing.JPanel studentPanel_;
	private javax.swing.JPanel marksPanel_;
	private javax.swing.JPanel gradePanel_;
	private javax.swing.JTextField assignment1Field_;
	private javax.swing.JTextField assignment2Field_;
	private javax.swing.JTextField examField_;
}
